### ISSUE TITLE
[BUG] Input box font?

### ISSUE THREAD

**Issue by Just-Moh-it** [harshhhdev/kmenu#8] opened 2022-07-30 12:37 UTC
**Describe the bug**

For some reason, the font looks very off in the text-box... as if it were the default font

**To Reproduce**
1. Just follow the setup instructions in the docs
2. Open the command palette and start typing to notice it

**Expected behavior**
<img width="898" alt="Screenshot 2022-07-30 at 6 05 45 PM" src="https://user-images.githubusercontent.com/48997634/181914535-7d644837-ed7e-458d-9b72-5b01bf8aa4fd.png">

**Actual Behaviour**
<img width="835" alt="Screenshot 2022-07-30 at 6 06 10 PM" src="https://user-images.githubusercontent.com/48997634/181914557-09bd0302-6cea-41b7-8cdb-eac238483d7e.png">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version: Chrome: 103.0, macOs 12.4

**Comment by Just-Moh-it** [comment] 2022-07-30 12:38
It's not that noticeable in the screenshots, but really stands out while typing stuff in the text box in an actual website

**Comment by harshhhdev** [comment] 2022-07-30 19:57
![image](https://user-images.githubusercontent.com/69592270/181989375-9e3ffd58-f086-42d9-9210-bfbdd2a83912.png)
![image](https://user-images.githubusercontent.com/69592270/181989663-77ab27fe-ede9-489b-9705-4c02024493c2.png)

I've done a comparison of the two, here are screenshots side by side of them. The only difference is the first one has a slightly larger font, which distorts the rendering a bit.

In the screenshot you have shown me, that's not a problem on kmenu's side -- it's a problem on your side. It's visible that the font in the input field is the default font, but the issue isn't with kmenu it's an issue with how browser styling works in-general.

By default, they do not inherit the font (the same is true with ALL form elements such as `button` or `select`), and that's something you can easily fix with some CSS. Just add in:

```css
/* I'm assuming the font you showed me is Poppins, just replace it if it's not */
input, select, textarea, button{ font-family: 'Poppins', sans-serif; }
```

However, I think it's a good idea for me to put `font-family: inherit` in the CSS of kmenu.

**Comment by harshhhdev** [comment] 2022-07-30 20:00
Fonts will be inherited by default on kmenu v1 :champagne:

**Closed** 2022-07-30 20:00 UTC
Labels: bug
